name: Build DraftGPT Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # You can specify the Python version here

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools

    - name: Build package
      run: |
        python -m pip install --upgrade build
        python -m build

    - name: Verify build
      run: |
        ls dist/
