# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
    inputs:
      chatgpt-api-key:
        description: 'chatgpt-api-key'
        required: false
        default: 'CHANGEME'
      choice:
        type: choice
        description: Choose gpt model
        options:
        - gpt-3.5-turbo
        - gpt-4
        - gpt-4-turbo
      message-link:
        description: 'Link to the Slack message'
        required: false
        default: 'Not necessary to include'
      slack-token:
        description: 'Slack api token'
        required: false
        default: 'Necessary if slack-link included'
      input_file_path:
        description: 'enter the path for input file'
        required: false


jobs:
  build:
    runs-on: ubuntu-latest
    environment: OPENAI_API_KEY
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        env:
          OPENAI_API_KEY: ${{github.event.inputs.chatgpt-api-key}}
          GPT_MODEL: ${{ github.event.inputs.choice }}
          MESSAGE_LINK: ${{ github.event.inputs.message-link }}
          SLACK_TOKEN: ${{ github.event.inputs.slack-token }}
            
          DRAFTGPT_INPUT_LOGFILE: ${{github.event.inputs.input_file_path}}
        run: |
          pytest
          python src/DraftGPT/test_draftgpt.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.txt
          path: report.txt
